[2025-03-30T14:00:03.448+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [queued]>
[2025-03-30T14:00:03.456+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [queued]>
[2025-03-30T14:00:03.456+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-30T14:00:03.468+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pyspark_consumer> on 2025-03-30 13:50:00+00:00
[2025-03-30T14:00:03.474+0000] {standard_task_runner.py:57} INFO - Started process 13597 to run task
[2025-03-30T14:00:03.478+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'scheduled__2025-03-30T13:50:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpam7uw8n6']
[2025-03-30T14:00:03.480+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask pyspark_consumer
[2025-03-30T14:00:03.531+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [running]> on host a6934a850e84
[2025-03-30T14:00:03.607+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T13:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T13:50:00+00:00'
[2025-03-30T14:00:03.609+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-30T14:00:03.610+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-server ./spark/bin/spark-submit ./kafkaToDelta.py']
[2025-03-30T14:00:03.624+0000] {subprocess.py:86} INFO - Output:
[2025-03-30T14:00:03.641+0000] {subprocess.py:93} INFO - Error response from daemon: No such container: spark-server
[2025-03-30T14:00:03.643+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-30T14:00:03.655+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T14:00:03.659+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250330T135000, start_date=20250330T140003, end_date=20250330T140003
[2025-03-30T14:00:03.671+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 133 for task pyspark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 13597)
[2025-03-30T14:00:03.696+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-30T14:00:03.713+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
