[2025-03-30T14:00:10.329+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [queued]>
[2025-03-30T14:00:10.336+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [queued]>
[2025-03-30T14:00:10.336+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-30T14:00:10.347+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pyspark_consumer> on 2025-03-30 13:50:00+00:00
[2025-03-30T14:00:10.353+0000] {standard_task_runner.py:57} INFO - Started process 13607 to run task
[2025-03-30T14:00:10.356+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'scheduled__2025-03-30T13:50:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpmo3yifwv']
[2025-03-30T14:00:10.359+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask pyspark_consumer
[2025-03-30T14:00:10.405+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:50:00+00:00 [running]> on host a6934a850e84
[2025-03-30T14:00:10.480+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T13:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T13:50:00+00:00'
[2025-03-30T14:00:10.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-30T14:00:10.483+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-server ./spark/bin/spark-submit ./kafkaToDelta.py']
[2025-03-30T14:00:10.497+0000] {subprocess.py:86} INFO - Output:
[2025-03-30T14:00:10.513+0000] {subprocess.py:93} INFO - Error response from daemon: No such container: spark-server
[2025-03-30T14:00:10.516+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-30T14:00:10.527+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T14:00:10.530+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250330T135000, start_date=20250330T140010, end_date=20250330T140010
[2025-03-30T14:00:10.541+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 134 for task pyspark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 13607)
[2025-03-30T14:00:10.572+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-30T14:00:10.589+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
