[2025-03-30T13:50:09.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:40:00+00:00 [queued]>
[2025-03-30T13:50:09.805+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:40:00+00:00 [queued]>
[2025-03-30T13:50:09.805+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-30T13:50:09.817+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pyspark_consumer> on 2025-03-30 13:40:00+00:00
[2025-03-30T13:50:09.823+0000] {standard_task_runner.py:57} INFO - Started process 8739 to run task
[2025-03-30T13:50:09.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'scheduled__2025-03-30T13:40:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpi9h6snhs']
[2025-03-30T13:50:09.828+0000] {standard_task_runner.py:85} INFO - Job 131: Subtask pyspark_consumer
[2025-03-30T13:50:09.874+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2025-03-30T13:40:00+00:00 [running]> on host a6934a850e84
[2025-03-30T13:50:09.957+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T13:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T13:40:00+00:00'
[2025-03-30T13:50:09.959+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-30T13:50:09.960+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-server ./spark/bin/spark-submit ./kafkaToDelta.py']
[2025-03-30T13:50:09.974+0000] {subprocess.py:86} INFO - Output:
[2025-03-30T13:50:09.994+0000] {subprocess.py:93} INFO - Error response from daemon: No such container: spark-server
[2025-03-30T13:50:09.996+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-30T13:50:10.007+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T13:50:10.010+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250330T134000, start_date=20250330T135009, end_date=20250330T135010
[2025-03-30T13:50:10.022+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 131 for task pyspark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 8739)
[2025-03-30T13:50:10.044+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-30T13:50:10.060+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
