[2025-03-29T16:36:54.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:34:23.598548+00:00 [queued]>
[2025-03-29T16:36:54.702+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:34:23.598548+00:00 [queued]>
[2025-03-29T16:36:54.703+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2025-03-29T16:36:54.718+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 16:34:23.598548+00:00
[2025-03-29T16:36:54.723+0000] {standard_task_runner.py:57} INFO - Started process 9906 to run task
[2025-03-29T16:36:54.727+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'manual__2025-03-29T16:34:23.598548+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpemgvsqbi']
[2025-03-29T16:36:54.732+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask kafka_data_stream
[2025-03-29T16:36:54.796+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:34:23.598548+00:00 [running]> on host 3737d644f467
[2025-03-29T16:36:54.891+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T16:34:23.598548+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T16:34:23.598548+00:00'
[2025-03-29T16:36:54.894+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafk_producer('development')
NameError: name 'create_kafk_producer' is not defined
[2025-03-29T16:36:54.907+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T163423, start_date=20250329T163654, end_date=20250329T163654
[2025-03-29T16:36:54.920+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task kafka_data_stream (name 'create_kafk_producer' is not defined; 9906)
[2025-03-29T16:36:54.943+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T16:36:54.974+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
