[2025-03-29T17:55:15.424+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:55:13.536083+00:00 [queued]>
[2025-03-29T17:55:15.436+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:55:13.536083+00:00 [queued]>
[2025-03-29T17:55:15.436+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-29T17:55:15.453+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 17:55:13.536083+00:00
[2025-03-29T17:55:15.460+0000] {standard_task_runner.py:57} INFO - Started process 24580 to run task
[2025-03-29T17:55:15.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'manual__2025-03-29T17:55:13.536083+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpo3s5iin7']
[2025-03-29T17:55:15.470+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask kafka_data_stream
[2025-03-29T17:55:15.553+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:55:13.536083+00:00 [running]> on host dde87091e389
[2025-03-29T17:55:15.648+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T17:55:13.536083+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T17:55:13.536083+00:00'
[2025-03-29T17:55:15.650+0000] {kafka_producer_util.py:30} INFO - Attempting to use KafkaProducer class: <class 'kafka.producer.kafka.KafkaProducer'>
[2025-03-29T17:55:15.651+0000] {kafka_producer_util.py:31} INFO - Imported from module: kafka.producer.kafka
[2025-03-29T17:55:15.651+0000] {kafka_producer_util.py:34} INFO - Top-level kafka module path: /home/***/.local/lib/python3.8/site-packages/kafka/__init__.py
[2025-03-29T17:55:16.973+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka-server:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-29T17:55:16.974+0000] {conn.py:315} ERROR - DNS lookup failed for kafka-server:9092 (0)
[2025-03-29T17:55:16.974+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-03-29T17:55:18.236+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka-server:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-29T17:55:18.237+0000] {conn.py:315} ERROR - DNS lookup failed for kafka-server:9092 (0)
[2025-03-29T17:55:18.237+0000] {kafka_producer_util.py:53} ERROR - Kafka Producer initialization failed: NoBrokersAvailable
[2025-03-29T17:55:18.237+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafka_publisher('development')
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 139, in create_kafka_publisher
    return KafkaPublisher(**config)
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 39, in __init__
    self.producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-29T17:55:18.248+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T175513, start_date=20250329T175515, end_date=20250329T175518
[2025-03-29T17:55:18.269+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task kafka_data_stream (NoBrokersAvailable; 24580)
[2025-03-29T17:55:18.316+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T17:55:18.344+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
