[2025-03-29T18:00:11.602+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T17:50:00+00:00 [queued]>
[2025-03-29T18:00:11.612+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T17:50:00+00:00 [queued]>
[2025-03-29T18:00:11.612+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-29T18:00:11.628+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 17:50:00+00:00
[2025-03-29T18:00:11.634+0000] {standard_task_runner.py:57} INFO - Started process 27001 to run task
[2025-03-29T18:00:11.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2025-03-29T17:50:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpkxnre4wu']
[2025-03-29T18:00:11.641+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask kafka_data_stream
[2025-03-29T18:00:11.699+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T17:50:00+00:00 [running]> on host dde87091e389
[2025-03-29T18:00:11.790+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T17:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T17:50:00+00:00'
[2025-03-29T18:00:11.792+0000] {kafka_producer_util.py:30} INFO - Attempting to use KafkaProducer class: <class 'kafka.producer.kafka.KafkaProducer'>
[2025-03-29T18:00:11.793+0000] {kafka_producer_util.py:31} INFO - Imported from module: kafka.producer.kafka
[2025-03-29T18:00:11.793+0000] {kafka_producer_util.py:34} INFO - Top-level kafka module path: /home/***/.local/lib/python3.8/site-packages/kafka/__init__.py
[2025-03-29T18:00:13.099+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka-server:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-29T18:00:13.100+0000] {conn.py:315} ERROR - DNS lookup failed for kafka-server:9092 (0)
[2025-03-29T18:00:13.100+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-03-29T18:00:14.349+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka-server:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-03-29T18:00:14.349+0000] {conn.py:315} ERROR - DNS lookup failed for kafka-server:9092 (0)
[2025-03-29T18:00:14.349+0000] {kafka_producer_util.py:53} ERROR - Kafka Producer initialization failed: NoBrokersAvailable
[2025-03-29T18:00:14.349+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafka_publisher('development')
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 139, in create_kafka_publisher
    return KafkaPublisher(**config)
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 39, in __init__
    self.producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-03-29T18:00:14.361+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T175000, start_date=20250329T180011, end_date=20250329T180014
[2025-03-29T18:00:14.375+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 52 for task kafka_data_stream (NoBrokersAvailable; 27001)
[2025-03-29T18:00:14.402+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T18:00:14.429+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
