[2025-03-29T17:35:40.075+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:35:38.348744+00:00 [queued]>
[2025-03-29T17:35:40.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:35:38.348744+00:00 [queued]>
[2025-03-29T17:35:40.090+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-29T17:35:40.111+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 17:35:38.348744+00:00
[2025-03-29T17:35:40.118+0000] {standard_task_runner.py:57} INFO - Started process 15152 to run task
[2025-03-29T17:35:40.127+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'manual__2025-03-29T17:35:38.348744+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp9txzzcjo']
[2025-03-29T17:35:40.130+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask kafka_data_stream
[2025-03-29T17:35:40.204+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T17:35:38.348744+00:00 [running]> on host dde87091e389
[2025-03-29T17:35:40.294+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T17:35:38.348744+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T17:35:38.348744+00:00'
[2025-03-29T17:35:40.296+0000] {kafka_producer_util.py:30} INFO - Attempting to use KafkaProducer class: <class 'kafka.producer.kafka.KafkaProducer'>
[2025-03-29T17:35:40.296+0000] {kafka_producer_util.py:31} INFO - Imported from module: kafka.producer.kafka
[2025-03-29T17:35:40.296+0000] {kafka_producer_util.py:34} INFO - Top-level kafka module path: /home/***/.local/lib/python3.8/site-packages/kafka/__init__.py
[2025-03-29T17:35:40.299+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka-server:9092 [('172.18.0.4', 9092) IPv4]
[2025-03-29T17:35:40.299+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-03-29T17:35:40.301+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-03-29T17:35:40.406+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-03-29T17:35:40.406+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-03-29T17:35:40.408+0000] {kafka_producer_util.py:48} INFO - KafkaProducer instantiated successfully.
[2025-03-29T17:35:40.412+0000] {api_data_collector.py:47} ERROR - API Request Error: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v2/random-data-list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f14174ab430>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-29T17:35:40.412+0000] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-03-29T17:35:40.414+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-03-29T17:35:40.415+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 89, in stream
    collector.process_and_publish(headers)
  File "/opt/airflow/dags/src/api_data_collector.py", line 69, in process_and_publish
    return false
NameError: name 'false' is not defined
[2025-03-29T17:35:40.425+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T173538, start_date=20250329T173540, end_date=20250329T173540
[2025-03-29T17:35:40.436+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task kafka_data_stream (name 'false' is not defined; 15152)
[2025-03-29T17:35:40.463+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T17:35:40.498+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
