[2025-03-29T17:00:08.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:50:00+00:00 [queued]>
[2025-03-29T17:00:08.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:50:00+00:00 [queued]>
[2025-03-29T17:00:08.919+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-29T17:00:08.933+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 16:50:00+00:00
[2025-03-29T17:00:08.939+0000] {standard_task_runner.py:57} INFO - Started process 21059 to run task
[2025-03-29T17:00:08.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2025-03-29T16:50:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpla9unq1f']
[2025-03-29T17:00:08.945+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask kafka_data_stream
[2025-03-29T17:00:08.997+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:50:00+00:00 [running]> on host 3737d644f467
[2025-03-29T17:00:09.072+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T16:50:00+00:00'
[2025-03-29T17:00:09.073+0000] {kafka_producer_util.py:41} ERROR - Kafka Producer initialization failed: __init__() got an unexpected keyword argument 'value_serializer'
[2025-03-29T17:00:09.074+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafka_producer('development')
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 127, in create_kafka_producer
    return KafkaProducer(**config)
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 31, in __init__
    self.producer = KafkaProducer(
TypeError: __init__() got an unexpected keyword argument 'value_serializer'
[2025-03-29T17:00:09.084+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T165000, start_date=20250329T170008, end_date=20250329T170009
[2025-03-29T17:00:09.094+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task kafka_data_stream (__init__() got an unexpected keyword argument 'value_serializer'; 21059)
[2025-03-29T17:00:09.121+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T17:00:09.148+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
