[2025-03-29T16:54:12.390+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:54:04.192037+00:00 [queued]>
[2025-03-29T16:54:12.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:54:04.192037+00:00 [queued]>
[2025-03-29T16:54:12.399+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-29T16:54:12.412+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 16:54:04.192037+00:00
[2025-03-29T16:54:12.418+0000] {standard_task_runner.py:57} INFO - Started process 18199 to run task
[2025-03-29T16:54:12.422+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'manual__2025-03-29T16:54:04.192037+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpzy3jlcpk']
[2025-03-29T16:54:12.424+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask kafka_data_stream
[2025-03-29T16:54:12.480+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-03-29T16:54:04.192037+00:00 [running]> on host 3737d644f467
[2025-03-29T16:54:12.562+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T16:54:04.192037+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T16:54:04.192037+00:00'
[2025-03-29T16:54:12.564+0000] {kafka_producer_util.py:41} ERROR - Kafka Producer initialization failed: __init__() got an unexpected keyword argument 'value_serializer'
[2025-03-29T16:54:12.565+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafka_producer('development')
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 127, in create_kafka_producer
    return KafkaProducer(**config)
  File "/opt/airflow/dags/src/kafka_producer_util.py", line 31, in __init__
    self.producer = KafkaProducer(
TypeError: __init__() got an unexpected keyword argument 'value_serializer'
[2025-03-29T16:54:12.575+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T165404, start_date=20250329T165412, end_date=20250329T165412
[2025-03-29T16:54:12.589+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task kafka_data_stream (__init__() got an unexpected keyword argument 'value_serializer'; 18199)
[2025-03-29T16:54:12.639+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T16:54:12.668+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
