[2025-03-30T03:40:02.087+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T03:30:00+00:00 [queued]>
[2025-03-30T03:40:02.098+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T03:30:00+00:00 [queued]>
[2025-03-30T03:40:02.098+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-30T03:40:02.109+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-30 03:30:00+00:00
[2025-03-30T03:40:02.117+0000] {standard_task_runner.py:57} INFO - Started process 58609 to run task
[2025-03-30T03:40:02.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2025-03-30T03:30:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp5mcfq3vh']
[2025-03-30T03:40:02.124+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask kafka_data_stream
[2025-03-30T03:40:02.184+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T03:30:00+00:00 [running]> on host a6934a850e84
[2025-03-30T03:40:02.279+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T03:30:00+00:00'
[2025-03-30T03:40:02.282+0000] {kafka_producer_util.py:30} INFO - Attempting to use KafkaProducer class: <class 'kafka.producer.kafka.KafkaProducer'>
[2025-03-30T03:40:02.282+0000] {kafka_producer_util.py:31} INFO - Imported from module: kafka.producer.kafka
[2025-03-30T03:40:02.282+0000] {kafka_producer_util.py:34} INFO - Top-level kafka module path: /home/***/.local/lib/python3.8/site-packages/kafka/__init__.py
[2025-03-30T03:40:02.284+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.20.0.2', 9092)]>: connecting to kafka-server:9092 [('172.20.0.2', 9092) IPv4]
[2025-03-30T03:40:02.284+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-03-30T03:40:02.285+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.20.0.2', 9092)]>: Connection complete.
[2025-03-30T03:40:02.388+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-03-30T03:40:02.388+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-03-30T03:40:02.390+0000] {kafka_producer_util.py:48} INFO - KafkaProducer instantiated successfully.
[2025-03-30T03:40:02.395+0000] {api_data_collector.py:47} ERROR - API Request Error: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v2/random-data-list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb74ad1c400>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-30T03:40:02.397+0000] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-03-30T03:40:02.399+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connected> [IPv4 ('172.20.0.2', 9092)]>: Closing connection. 
[2025-03-30T03:40:02.400+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-30T03:40:02.410+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250330T033000, start_date=20250330T034002, end_date=20250330T034002
[2025-03-30T03:40:02.460+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-30T03:40:02.487+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
