[2025-03-29T16:34:31.964+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:20:00+00:00 [queued]>
[2025-03-29T16:34:31.972+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:20:00+00:00 [queued]>
[2025-03-29T16:34:31.972+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-03-29T16:34:31.985+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-29 16:20:00+00:00
[2025-03-29T16:34:31.990+0000] {standard_task_runner.py:57} INFO - Started process 8697 to run task
[2025-03-29T16:34:31.993+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2025-03-29T16:20:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp_647fsbe']
[2025-03-29T16:34:31.996+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask kafka_data_stream
[2025-03-29T16:34:32.049+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-29T16:20:00+00:00 [running]> on host 3737d644f467
[2025-03-29T16:34:32.182+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T16:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T16:20:00+00:00'
[2025-03-29T16:34:32.189+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/api_data_collector.py", line 75, in stream
    kafka_publisher = create_kafka_publisher('development')
NameError: name 'create_kafka_publisher' is not defined
[2025-03-29T16:34:32.205+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250329T162000, start_date=20250329T163431, end_date=20250329T163432
[2025-03-29T16:34:32.226+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task kafka_data_stream (name 'create_kafka_publisher' is not defined; 8697)
[2025-03-29T16:34:32.253+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-29T16:34:32.285+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
